### ISSUE TITLE
Support for tuya 3.4 devices

### ISSUE THREAD

**Issue by davidfrickert** [rkosegi/tuya-smartplug-exporter#132]
Hi,

I was trying to use your project to gather data from my smart plugs which are Tuya 3.4, but it doesn't seem like this project works with it (different payload format).

Would you consider adding support for it? I tried playing around but couldn't really get it to work.

The format is more or less documented in the python project https://github.com/jasonacox/tinytuya

**Comment by rkosegi** [comment]
Hi @davidfrickert,
thank you for opening issue.
This has been asked previously, eg [here](https://github.com/rkosegi/tuya-smartplug-exporter/issues/87#issuecomment-2515305024).
Thing is, that I don't have 3.4 device at my disposal, so I won't do anything about it.

PRs are always welcome.

**Comment by davidfrickert** [comment]
understandable, i don't have enough expertise in this kind of stuff to know how to fix it, so I just built a simple python Webserver that uses the tinytuya module to communicate with my devices and adapted this project to call that service. seems to work fine for me !
