### ISSUE TITLE
Error during scrape

### ISSUE THREAD

**Issue by Jared0430** [rkosegi/tuya-smartplug-exporter#87]
Hi, I have just purchased some Tuya smart plugs and am trying to get them connected with this package.

I grabbed my local keys using `npx @tuyapi/cli wizard` and setup my config file, but I am getting this error every time I try to scrape

```
ts=2024-05-10T16:59:24.467Z caller=exporter.go:56 level=warn msg="error during scrape" device=PC error=EOF
ts=2024-05-10T16:59:24.673Z caller=exporter.go:56 level=warn msg="error during scrape" device=AC error=EOF
ts=2024-05-10T16:59:24.867Z caller=exporter.go:56 level=warn msg="error during scrape" device=Server error=EOF
```

Let me know if there's a way I can get more info and thanks for the help!

EDIT: I've done some tracing and the issue is coming from `pkg/proto/client.go`:

```go
func (p *proto) exchange() ([]byte, error) {
        // ...

	inbuffer := make([]byte, 256)
	read, err := conn.Read(inbuffer) // <--
```

if that helps debug the issue, I'm not very familiar with Go

**Comment by rkosegi** [comment]
Hi @Jared0430, `EOF` during read means that device closed connection before read completes. Not sure what to do with that :man_shrugging:

**Comment by Jared0430** [comment]
I also tried connecting to my device with [codetheweb/tuyapi](https://github.com/codetheweb/tuyapi) and am getting a similar issue, with the socket being immediately closed. It seems this may be a problem with Tuya protocol version 3.4.

After applying the fix from https://github.com/helberhlm/tuyapi/commit/bd28e0febd9628bf22f5adb02732dc778521bed6 the connection seems to work correctly.

**Comment by Mistikan** [comment]
Hello!
Unfortunately, I had the same error as the author. I dug deeper and am ready to give my comment.

My equipment:
* Device: Atorch S1-B/W/T/H
* Main module version: V2.1.6
* Microcontroller module version: v1.0.7

By experimenting with the Python library (https://github.com/jasonacox/tinytuya), I realized that my device communicates via protocol 3.4.

Unfortunately, your repository does not support this protocol.

I won't keep you in suspense - I forked the person's repository, modified it, and now I have a similarly functional exporter for rust.

Link: https://github.com/Mistikan/tuya-web

Please, don't consider this as advertising - suddenly someone will be looking for a solution to the problem.
Thank you very much for your developments - I was guided by them when solving my problem.

**Comment by rkosegi** [comment]
@Mistikan, thanks for sharing your repo, great to hear that you made it work.
One day, if I will have device that talks by 3.4 protocol I might use it for inspiration ;)
