### ISSUE TITLE
Image does not work on ARM64 architecture

### ISSUE THREAD

**Issue by Flexba** [rkosegi/tuya-smartplug-exporter#88]
As I tried setting up the exporter on my Raspberry Pi, the following errors are displayed:

```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
exec /exporter: exec format error
```

Having looked into the Github Workflow file publish-image.yaml, this image appears to be only built for AMD64.

I can't promise to find time for it in the next weeks but I'll try to create a small PR with the change to release it on ARM64 and AMD64 if you don't mind.

**Comment by rkosegi** [comment]
Thanks @Flexba for PR!
